name: remote SSH test
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEVSERVER_HOST }}
          username: ${{ secrets.DEVSERVER_USERNAME }}
          password: ${{ secrets.DEVSERVER_PASSWORD }}
          port: ${{ secrets.DEVSERVER_PORT }}
          script: |
            cd wb-web-app
            git pull
            yarn install
            yarn build
            echo ${{ secrets.PASSWORD }} | sudo -S systemctl restart nginx
