name: Development Server Deployment
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: update local files
        run: |
          cd /home/${{ secrets.DEVSERVER_USERNAME }}/wb-web-app
          git pull
      - name: Build react project to static files
        run: |
          cd /home/${{ secrets.DEVSERVER_USERNAME }}/wb-web-app
          git checkout main
          yarn install
          yarn build
  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Copy the build product to ROOT of tomcat webapps routes
        run: |
          echo ${{ secrets.DEVSERVER_PASSWORD }} | sudo -S rm -rf /home/${{ secrets.DEVSERVER_USERNAME }}/tomcat/webapps/ROOT
          sudo mkdir /home/${{ secrets.DEVSERVER_USERNAME }}/tomcat/webapps/ROOT
          sudo cp -R /home/${{ secrets.DEVSERVER_USERNAME }}/wb-web-app/build/* /home/${{ secrets.DEVSERVER_USERNAME }}/tomcat/webapps/ROOT
      - name: Restart tomcat
        run: |
          echo ${{ secrets.DEVSERVER_PASSWORD }} | sudo -S /home/${{ secrets.DEVSERVER_USERNAME }}/tomcat/bin/shutdown.sh
          sudo /home/${{ secrets.DEVSERVER_USERNAME }}/tomcat/bin/startup.sh