name: Build Production Web App
on: 
  pull_request:
    types:
    - closed
    branches:
    - production
jobs:
  if_merged:
    name: Check if the pull request was merged
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Check if PR was merged.
        run: |
          echo "PR WAS MERGED TO PRODUCTION. START DEPLOYMENT."
  build:
    needs: if_merged
    name: Build
    runs-on: self-hosted
    steps:
      - name: update local files
        run: |
          cd /home/yany/wb-web-app
          git pull
      - name: Build react project to static files
        run: |
          cd /home/yany/wb-web-app
          git checkout production
          yarn install
          yarn build
  deploy:
    needs: build
    name: 🎉 Deploy
    runs-on: self-hosted
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.PRODSERVER_HOST }}/tomcat/webapps/ROOT
        username: ${{ secrets.PRODSERVER_USERNAME }}
        password: ${{ secrets.PRODSERVER_PASSWORD }}
        local-dir: /home/${{ secrets.DEVSERVER_USERNAME }}/wb-web-app/build/
